<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-17T01:28:26 EST" name="Default suite" finished-at="2024-11-17T01:28:29 EST" duration-ms="2306">
    <groups>
    </groups>
    <test started-at="2024-11-17T01:28:26 EST" name="Default test" finished-at="2024-11-17T01:28:29 EST" duration-ms="2306">
      <class name="pageTestEvents.TreePageEvents">
        <test-method is-config="true" signature="setUP()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:24 EST" name="setUP" finished-at="2024-11-17T01:28:26 EST" duration-ms="2053" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method is-config="true" signature="Login()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:26 EST" name="Login" finished-at="2024-11-17T01:28:27 EST" duration-ms="1002" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="treePage()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:27 EST" name="treePage" finished-at="2024-11-17T01:28:28 EST" duration-ms="267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- treePage -->
        <test-method signature="practiceQue()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:28 EST" name="practiceQue" finished-at="2024-11-17T01:28:28 EST" duration-ms="446" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at pageTestEvents.TreePageEvents.practiceQue(TreePageEvents.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- practiceQue -->
        <test-method is-config="true" signature="backtostack()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:28 EST" name="backtostack" finished-at="2024-11-17T01:28:28 EST" duration-ms="212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backtostack -->
        <test-method is-config="true" signature="Logout()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:28 EST" name="Logout" finished-at="2024-11-17T01:28:29 EST" duration-ms="272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pageTestEvents.TreePageEvents@51a9ad5e]" started-at="2024-11-17T01:28:29 EST" name="tearDown" finished-at="2024-11-17T01:28:29 EST" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pageTestEvents.TreePageEvents -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
