<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anvi" failures="2" tests="30" name="pageTestEvents.GraphPageEvents" time="62.839" errors="0" timestamp="2024-11-16T18:23:51 CST" skipped="0">
  <testcase classname="pageTestEvents.GraphPageEvents" name="validCodeGraph" time="6.704"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="tryHereGraphRepresentation" time="1.423"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="queuePageT1" time="1.468"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="arrayPageT2" time="1.496"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="treePageT1" time="1.633"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="nocodeGraph" time="1.407"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="graphDdropDown" time="1.123"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="invalidCodeGraph" time="7.350"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="tryHereGraph" time="1.542"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="queuePageT2" time="1.438"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="linkedListPageT1" time="1.357"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="stackPageT2" time="1.407"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="validCodeGraphRep" time="6.746"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="stackPageT1" time="1.481"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="nocodeGraphRepresentation" time="1.577"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="stackPage" time="1.116"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="invalidCodeGraphRep" time="6.792"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="practiceQueT1" time="1.361">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at pageTestEvents.GraphPageEvents.practiceQueT1(GraphPageEvents.java:165)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- practiceQueT1 -->
  <testcase classname="pageTestEvents.GraphPageEvents" name="treePage" time="1.292"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="linkedListPage" time="1.204"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="arrayPageT1" time="1.317"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="graphDdropDownT2" time="1.467"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="linkedListPageT2" time="1.331"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="practiceQueT2" time="1.390">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at pageTestEvents.GraphPageEvents.practiceQueT2(GraphPageEvents.java:176)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- practiceQueT2 -->
  <testcase classname="pageTestEvents.GraphPageEvents" name="arrayPage" time="1.197"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="treePageT2" time="1.496"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="queuePage" time="1.291"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="graphDdropDownT1" time="1.437"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="graphTopic" time="0.978"/>
  <testcase classname="pageTestEvents.GraphPageEvents" name="graphRepresentationTopic" time="1.018"/>
</testsuite> <!-- pageTestEvents.GraphPageEvents -->
